name: 'Use Pulumi ESC Values'
description: 'Use Pulumi ESC Values in GitHub Actions'
author: 'jaxxstorm'

# Define your inputs here.
inputs:
  access-token:
    description: 'The Pulumi access token to use'
    required: true
  org-name:
    description: 'The org name to retrieve environments from'
    required: true
  environment:
    description: 'The Pulumi ESC environment to open'
    required: true

branding:
  icon: "archive"
  color: "green"

runs:
  using: node20
  main: dist/index.js
